title: Aishwary Joshi's Portfolio
description: >-
  Data Engineer and Business Analyst with experience in transforming data into actionable insights.
url: "https://aishwaryjoshi.github.io"
baseurl: ""

# Social Links
github_username: aishwaryjoshi
linkedin_username: aishwary-joshi-7336b4105

# Theme settings
theme: minima

# SEO settings
seo:
  title: "Aishwary Joshi's Portfolio"
  description: "Data Engineer and Business Analyst"
  author: Aishwary Joshi
  url: "https://aishwaryjoshi.github.io"
